// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: banking.proto

package banking;

public final class Banking {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_banking_ChargeCardRequest_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_banking_ChargeCardRequest_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_banking_ChargeCardResponse_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_banking_ChargeCardResponse_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        String[] descriptorData = {
                "\n\rbanking.proto\022\007banking\"7\n\021ChargeCardRe" +
                        "quest\022\022\n\ncardNumber\030\001 \001(\t\022\016\n\006amount\030\002 \001(" +
                        "\005\"%\n\022ChargeCardResponse\022\017\n\007success\030\001 \001(\010" +
                        "b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_banking_ChargeCardRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_banking_ChargeCardRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_banking_ChargeCardRequest_descriptor,
                new String[]{"CardNumber", "Amount",});
        internal_static_banking_ChargeCardResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_banking_ChargeCardResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_banking_ChargeCardResponse_descriptor,
                new String[]{"Success",});
    }

    private Banking() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    public interface ChargeCardRequestOrBuilder extends
            // @@protoc_insertion_point(interface_extends:banking.ChargeCardRequest)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>string cardNumber = 1;</code>
         */
        String getCardNumber();

        /**
         * <code>string cardNumber = 1;</code>
         */
        com.google.protobuf.ByteString
        getCardNumberBytes();

        /**
         * <code>int32 amount = 2;</code>
         */
        int getAmount();
    }

    public interface ChargeCardResponseOrBuilder extends
            // @@protoc_insertion_point(interface_extends:banking.ChargeCardResponse)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>bool success = 1;</code>
         */
        boolean getSuccess();
    }

    /**
     * Protobuf type {@code banking.ChargeCardRequest}
     */
    public static final class ChargeCardRequest extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:banking.ChargeCardRequest)
            ChargeCardRequestOrBuilder {
        public static final int CARDNUMBER_FIELD_NUMBER = 1;
        public static final int AMOUNT_FIELD_NUMBER = 2;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:banking.ChargeCardRequest)
        private static final ChargeCardRequest DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<ChargeCardRequest>
                PARSER = new com.google.protobuf.AbstractParser<ChargeCardRequest>() {
            public ChargeCardRequest parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ChargeCardRequest(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new ChargeCardRequest();
        }

        private volatile Object cardNumber_;
        private int amount_;
        private byte memoizedIsInitialized = -1;

        // Use ChargeCardRequest.newBuilder() to construct.
        private ChargeCardRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ChargeCardRequest() {
            cardNumber_ = "";
            amount_ = 0;
        }

        private ChargeCardRequest(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 10: {
                            String s = input.readStringRequireUtf8();

                            cardNumber_ = s;
                            break;
                        }
                        case 16: {

                            amount_ = input.readInt32();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Banking.internal_static_banking_ChargeCardRequest_descriptor;
        }

        public static ChargeCardRequest parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChargeCardRequest parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChargeCardRequest parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChargeCardRequest parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChargeCardRequest parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChargeCardRequest parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChargeCardRequest parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ChargeCardRequest parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChargeCardRequest parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChargeCardRequest parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ChargeCardRequest prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ChargeCardRequest getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ChargeCardRequest> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Banking.internal_static_banking_ChargeCardRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ChargeCardRequest.class, Builder.class);
        }

        /**
         * <code>string cardNumber = 1;</code>
         */
        public String getCardNumber() {
            Object ref = cardNumber_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                cardNumber_ = s;
                return s;
            }
        }

        /**
         * <code>string cardNumber = 1;</code>
         */
        public com.google.protobuf.ByteString
        getCardNumberBytes() {
            Object ref = cardNumber_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                cardNumber_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>int32 amount = 2;</code>
         */
        public int getAmount() {
            return amount_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (!getCardNumberBytes().isEmpty()) {
                com.google.protobuf.GeneratedMessageV3.writeString(output, 1, cardNumber_);
            }
            if (amount_ != 0) {
                output.writeInt32(2, amount_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (!getCardNumberBytes().isEmpty()) {
                size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, cardNumber_);
            }
            if (amount_ != 0) {
                size += com.google.protobuf.CodedOutputStream
                        .computeInt32Size(2, amount_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ChargeCardRequest)) {
                return super.equals(obj);
            }
            ChargeCardRequest other = (ChargeCardRequest) obj;

            boolean result = true;
            result = result && getCardNumber()
                    .equals(other.getCardNumber());
            result = result && (getAmount()
                    == other.getAmount());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + CARDNUMBER_FIELD_NUMBER;
            hash = (53 * hash) + getCardNumber().hashCode();
            hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
            hash = (53 * hash) + getAmount();
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ChargeCardRequest> getParserForType() {
            return PARSER;
        }

        public ChargeCardRequest getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code banking.ChargeCardRequest}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:banking.ChargeCardRequest)
                ChargeCardRequestOrBuilder {
            private Object cardNumber_ = "";
            private int amount_;

            // Construct using banking.Banking.ChargeCardRequest.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Banking.internal_static_banking_ChargeCardRequest_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Banking.internal_static_banking_ChargeCardRequest_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ChargeCardRequest.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                cardNumber_ = "";

                amount_ = 0;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Banking.internal_static_banking_ChargeCardRequest_descriptor;
            }

            public ChargeCardRequest getDefaultInstanceForType() {
                return ChargeCardRequest.getDefaultInstance();
            }

            public ChargeCardRequest build() {
                ChargeCardRequest result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ChargeCardRequest buildPartial() {
                ChargeCardRequest result = new ChargeCardRequest(this);
                result.cardNumber_ = cardNumber_;
                result.amount_ = amount_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ChargeCardRequest) {
                    return mergeFrom((ChargeCardRequest) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ChargeCardRequest other) {
                if (other == ChargeCardRequest.getDefaultInstance()) return this;
                if (!other.getCardNumber().isEmpty()) {
                    cardNumber_ = other.cardNumber_;
                    onChanged();
                }
                if (other.getAmount() != 0) {
                    setAmount(other.getAmount());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ChargeCardRequest parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ChargeCardRequest) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>string cardNumber = 1;</code>
             */
            public String getCardNumber() {
                Object ref = cardNumber_;
                if (!(ref instanceof String)) {
                    com.google.protobuf.ByteString bs =
                            (com.google.protobuf.ByteString) ref;
                    String s = bs.toStringUtf8();
                    cardNumber_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }

            /**
             * <code>string cardNumber = 1;</code>
             */
            public Builder setCardNumber(
                    String value) {
                if (value == null) {
                    throw new NullPointerException();
                }

                cardNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string cardNumber = 1;</code>
             */
            public com.google.protobuf.ByteString
            getCardNumberBytes() {
                Object ref = cardNumber_;
                if (ref instanceof String) {
                    com.google.protobuf.ByteString b =
                            com.google.protobuf.ByteString.copyFromUtf8(
                                    (String) ref);
                    cardNumber_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>string cardNumber = 1;</code>
             */
            public Builder setCardNumberBytes(
                    com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                checkByteStringIsUtf8(value);

                cardNumber_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>string cardNumber = 1;</code>
             */
            public Builder clearCardNumber() {

                cardNumber_ = getDefaultInstance().getCardNumber();
                onChanged();
                return this;
            }

            /**
             * <code>int32 amount = 2;</code>
             */
            public int getAmount() {
                return amount_;
            }

            /**
             * <code>int32 amount = 2;</code>
             */
            public Builder setAmount(int value) {

                amount_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>int32 amount = 2;</code>
             */
            public Builder clearAmount() {

                amount_ = 0;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:banking.ChargeCardRequest)
        }

    }

    /**
     * Protobuf type {@code banking.ChargeCardResponse}
     */
    public static final class ChargeCardResponse extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:banking.ChargeCardResponse)
            ChargeCardResponseOrBuilder {
        public static final int SUCCESS_FIELD_NUMBER = 1;
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:banking.ChargeCardResponse)
        private static final ChargeCardResponse DEFAULT_INSTANCE;
        private static final com.google.protobuf.Parser<ChargeCardResponse>
                PARSER = new com.google.protobuf.AbstractParser<ChargeCardResponse>() {
            public ChargeCardResponse parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ChargeCardResponse(input, extensionRegistry);
            }
        };

        static {
            DEFAULT_INSTANCE = new ChargeCardResponse();
        }

        private boolean success_;
        private byte memoizedIsInitialized = -1;

        // Use ChargeCardResponse.newBuilder() to construct.
        private ChargeCardResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ChargeCardResponse() {
            success_ = false;
        }

        private ChargeCardResponse(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            int mutable_bitField0_ = 0;
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        default: {
                            if (!input.skipField(tag)) {
                                done = true;
                            }
                            break;
                        }
                        case 8: {

                            success_ = input.readBool();
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return Banking.internal_static_banking_ChargeCardResponse_descriptor;
        }

        public static ChargeCardResponse parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChargeCardResponse parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChargeCardResponse parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static ChargeCardResponse parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static ChargeCardResponse parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChargeCardResponse parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChargeCardResponse parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static ChargeCardResponse parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static ChargeCardResponse parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static ChargeCardResponse parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(ChargeCardResponse prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static ChargeCardResponse getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ChargeCardResponse> parser() {
            return PARSER;
        }

        @Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
        }

        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return Banking.internal_static_banking_ChargeCardResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            ChargeCardResponse.class, Builder.class);
        }

        /**
         * <code>bool success = 1;</code>
         */
        public boolean getSuccess() {
            return success_;
        }

        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (success_ != false) {
                output.writeBool(1, success_);
            }
        }

        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (success_ != false) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBoolSize(1, success_);
            }
            memoizedSize = size;
            return size;
        }

        @Override
        public boolean equals(final Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof ChargeCardResponse)) {
                return super.equals(obj);
            }
            ChargeCardResponse other = (ChargeCardResponse) obj;

            boolean result = true;
            result = result && (getSuccess()
                    == other.getSuccess());
            return result;
        }

        @Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                    getSuccess());
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        public Builder newBuilderForType() {
            return newBuilder();
        }

        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @Override
        protected Builder newBuilderForType(
                BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @Override
        public com.google.protobuf.Parser<ChargeCardResponse> getParserForType() {
            return PARSER;
        }

        public ChargeCardResponse getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code banking.ChargeCardResponse}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:banking.ChargeCardResponse)
                ChargeCardResponseOrBuilder {
            private boolean success_;

            // Construct using banking.Banking.ChargeCardResponse.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return Banking.internal_static_banking_ChargeCardResponse_descriptor;
            }

            protected FieldAccessorTable
            internalGetFieldAccessorTable() {
                return Banking.internal_static_banking_ChargeCardResponse_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                ChargeCardResponse.class, Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            public Builder clear() {
                super.clear();
                success_ = false;

                return this;
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return Banking.internal_static_banking_ChargeCardResponse_descriptor;
            }

            public ChargeCardResponse getDefaultInstanceForType() {
                return ChargeCardResponse.getDefaultInstance();
            }

            public ChargeCardResponse build() {
                ChargeCardResponse result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            public ChargeCardResponse buildPartial() {
                ChargeCardResponse result = new ChargeCardResponse(this);
                result.success_ = success_;
                onBuilt();
                return result;
            }

            public Builder clone() {
                return (Builder) super.clone();
            }

            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.setField(field, value);
            }

            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return (Builder) super.clearField(field);
            }

            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return (Builder) super.clearOneof(oneof);
            }

            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, Object value) {
                return (Builder) super.setRepeatedField(field, index, value);
            }

            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    Object value) {
                return (Builder) super.addRepeatedField(field, value);
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof ChargeCardResponse) {
                    return mergeFrom((ChargeCardResponse) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(ChargeCardResponse other) {
                if (other == ChargeCardResponse.getDefaultInstance()) return this;
                if (other.getSuccess() != false) {
                    setSuccess(other.getSuccess());
                }
                onChanged();
                return this;
            }

            public final boolean isInitialized() {
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                ChargeCardResponse parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (ChargeCardResponse) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>bool success = 1;</code>
             */
            public boolean getSuccess() {
                return success_;
            }

            /**
             * <code>bool success = 1;</code>
             */
            public Builder setSuccess(boolean value) {

                success_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>bool success = 1;</code>
             */
            public Builder clearSuccess() {

                success_ = false;
                onChanged();
                return this;
            }

            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }

            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return this;
            }


            // @@protoc_insertion_point(builder_scope:banking.ChargeCardResponse)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
